name = "Configurations"
uuid = "5218b696-f38b-4ac9-8b61-a12ec717816d"
authors = ["Roger-luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.13.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Expronicon = "6b7a57c9-7cc1-4fdf-b7f5-e857abae3636"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Crayons = "4.0"
Expronicon = "0.4"
OrderedCollections = "1.3"
TOML = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
